### ISSUE TITLE
Checkpoint 2 is Ready for Review

### ISSUE THREAD

**Issue by SapphireStar31** [SapphireStar31/recipe-searcher#2]
@pawaitemadisoncollege

Tests are all up and running and have full coverage of the DAO. Also, no system out print lines are in my code.

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31 

You've made some good progress with your indie project!  My notes from a review of your project for checkpoint 2 are below. In general you've hit the mark and are in a good position for this point in the semester. Most of comments below are related to things to keep in mind for completion in the near future, the only one required for "met" completion is related to the ERD:

**Database designed and created** 

I can see sql for your database, which looks good from what I can tell. The user table may not be represented yet. It would be easier for me to review if I can look at a current ERD.... so:

- [x] Can you share your current ERD so that I can review the full database design? The database view in IntelliJ can produce this if you don't have a preferred way of generating it already.

**DAO**

GenericDao implemented. CRUD Dao unit testing completed on two entities.

- [x] Be sure to test what happens to the "other side" when a recipe or ingredient is deleted. 

**Log4J is implemented (no System.out.printlns)**

I noticed one place where the stack traces are being printed to the console: https://github.com/SapphireStar31/recipe-searcher/blob/916b64f51c7ea75a244ef267677f06dbb6a71bb2/src/test/java/utilities/PropertiesLoader.java#L26-L32. It'd be better to throw these exceptions up to the caller so they can  be logged. 

**Time log and Plan**

This is up-to-date through  week 9 (with items checked off in the plan).

- [ ] Consider adding more specific tasks for the upcoming weeks now that you likely have a better idea of what needs to be done.

****Checkpoint 2: not met**  - I'd just like to review the ERD and then this will be met.**  

Let me know if you have any questions!

**Comment by SapphireStar31** [comment]
@pawaitemadisoncollege 
![ERD Diagram](https://github.com/user-attachments/assets/7965ac47-b389-4e2e-8bb3-92ebe84bb3f1)
Here is my ERD with the User table added in.

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31 - Thanks for sharing your ERD. The user table shouldn't need a password column as cognito takes care of that, but everything else looks good!

**cp2: met**
