### ISSUE TITLE
Checkpoint 3 Ready for Review

### ISSUE THREAD

**Issue by SapphireStar31** [SapphireStar31/recipe-searcher#4]
@pawaitemadisoncollege

http://recipe-searcher.us-east-2.elasticbeanstalk.com/

Project is up and running on AWS and has Cognito added in. I haven't added it the the Student repository yet since I was gonna pretty it up a little before I did that. Also I am getting charged for the Elastic Beanstalk I noticed even if I put the database to be micro and not small. Do you know if there is any thing else I can check to get rid of the costs? Its not a ton its charging me, but just wanna see if I can cut it all out if possible.

**Comment by pawaitemadisoncollege** [comment]
Hi @SapphireStar31! 

I've been struggling to figure out the cause for the EB charges - I am not free tier eligible so it's been hard for me to test this.  Now that you've hit this checkpoint, it is a-ok to remove the application so that you aren't charged. If you do want to keep poking at it, it also might be worth asking this slack - I think Dmitrii may have posted about and possibly resolved this. 

I was able to sign up on your was-deployed app and was able to see data out there. Things are really coming along and you've clearly **MET checkpoint 3** deliverables!!!

I also took a few minutes to review your code base to date and observed a lot of good work and best practices, such as using properties for your api key and aws values.

A few things to polish this up:

- [x] In add/update/delete scenarios, this would generally be a post, rather than a get: https://github.com/SapphireStar31/recipe-searcher/blob/e66e3ca9bbf3ab6b711d0b951df26c2de3e60405/src/main/java/controller/AddRecipe.java#L37
- [x] The method above is also doing quite a lot of work and would be easier to read/maintain if it were refactored into smaller single purpose methods. 
- [x] The "add input field" button would be better named something like "add ingredient field" or "add another ingredient". 
- [x] If you put the entire User object in the session after the user logs in, you could cut out this bit of code: https://github.com/SapphireStar31/recipe-searcher/blob/e66e3ca9bbf3ab6b711d0b951df26c2de3e60405/src/main/java/controller/AddRecipe.java#L82-L84.
- [x] I noticed some very long import lists in some classes - you could shorten these up by using a `*` to import all classes in the package. 
- [x] Can you avoid using scriptlets like this: https://github.com/SapphireStar31/recipe-searcher/blob/e66e3ca9bbf3ab6b711d0b951df26c2de3e60405/src/main/webapp/addNewRecipe.jsp#L6-L11? A couple thoughts: 1. use jstl or 2. route through a servlet so you can do this check in java code.

Let me know if you have any questions about the items above or anything else. Really good work here @SapphireStar31! Looking forward to seeing the final version!!!
